version: 2.1

executors:
  rust_executor:
    docker:
      - image: rustlang/rust:nightly-alpine3.12

jobs:
  build:
    executor: rust_executor
    steps:
      - run:
          command: apk add musl-dev
      - checkout
      - restore_cache:
          key: metro--{{ .Branch }}--{{ .Revision }}
      - run: cargo build
      - save_cache:
          key: metro--{{ .Branch }}--{{ .Revision }}
          paths:
            - /root/
            - /usr/local/cargo

  check_formatting:
    executor: rust_executor
    steps:
      - restore_cache:
          key: metro--{{ .Branch }}--{{ .Revision }}
      - run: cargo fmt -- --check

  lint:
    executor: rust_executor
    steps:
      - restore_cache:
          key: metro--{{ .Branch }}--{{ .Revision }}
      - run: cargo clippy -- -D warnings

  test:
    executor: rust_executor
    steps:
      - restore_cache:
          key: metro--{{ .Branch }}--{{ .Revision }}
      - run: cargo test

workflows:
  build_and_test:
    jobs:
      - build
      - check_formatting:
          requires:
            - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
